cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
    credentials:
      access-key: localstack_sqs
      secret-key: localstack_sqs
    end-point:
      uri: http://localhost:4566
sqs:
  queue-1: queue-process-object
  queue-2: queue-process-list-object
  queue-3: queue-process-string
