version: '3.5'

services:
  dynamodb:
    image: localstack/localstack:0.12.5
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=macking_key
      - AWS_SECRET_ACCESS_KEY=macking_user
    ports:
      - '4566:4566'